export const data = [
    {
        Id: 37843,
        Codigo: "UNMSM",
        Registro: 21213,
        Nombre: 'ALFREDO VELASQUEZ FLORES',
        Dni: 70038088,
        Categoria: "Curso",
        Programa: "Formulación y Evaluación de Proyetctos",
        Mes: "1/2020",
    },
    {
        Id: 10417,
        Codigo: "UNMSM",
        Registro: 21210,
        Nombre: 'JOSE NEISEL CABRERA VEGA',
        Dni: 80293700,
        Categoria: "Curso",
        Programa: "Formulación y Evaluación de Proyetctos",
        Mes: "1/2020",
    },
    {
        Id: 10416,
        Codigo: "UNMSM",
        Registro: 21196,
        Nombre: 'JOSE NEISEL CABRERA VEGA',
        Dni: 80293700,
        Categoria: "Curso",
        Programa: "ETT Y TDR para compras eficientes",
        Mes: "1/2020",
    },
    {
        Id: 21199,
        Codigo: "UNMSM",
        Registro: 21196,
        Nombre: 'RIQUE BABILONIA ESTRADA',
        Dni: 5379138,
        Categoria: "Curso",
        Programa: "Formulación y Evaluación de Proyetctos",
        Mes: "1/2020",
    },
    {
        Id: 21171,
        Codigo: "UNMSM",
        Registro: 21196,
        Nombre: 'ROSSE MARIE VASQUEZ OROYA',
        Dni: 44032884,
        Categoria: "Curso",
        Programa: "Planeamiento estrategico segun Ceplan",
        Mes: "1/2020",
    },
    {
        Id: 10412,
        Codigo: "UNMSM",
        Registro: 21196,
        Nombre: 'MARIA TERESA CHUCHON OCHOA',
        Dni: 72790299,
        Categoria: "Curso",
        Programa: "Planeamiento estrategico segun Ceplan",
        Mes: "1/2020",
    },
    {
        Id: 13772,
        Codigo: "CCDGG",
        Registro: 23337,
        Nombre: 'LILIBETH EMILY GOMERO LOPEZ',
        Dni: 41530756,
        Categoria: "Diploma",
        Programa: "Contrataciones del estado, Osce y Seace 3.0",
        Mes: "1/2020",
    },
    {
        Id: 4928,
        Codigo: "CCDG-012",
        Registro: 14441,
        Nombre: 'LEYDA NIEVES NAVINTA TUMBA',
        Dni: 493169,
        Categoria: "CURSO",
        Programa: "SIAF BASICO",
        Mes: "2/2019",
    },
    {
        Id: 4927,
        Codigo: "CCDG-009",
        Registro: 14438,
        Nombre: 'JOANA NUÑEZ ZEGARRA',
        Dni: 70435454,
        Categoria: "CURSO",
        Programa: "SIGA LOGISTICO",
        Mes: "2/2019",
    },
    {
        Id: 4926,
        Codigo: "CCDG-006",
        Registro: 14435,
        Nombre: 'NORY GODOY CAROCANCHA',
        Dni: 25849228,
        Categoria: "CURSO",
        Programa: "SIGA LOGISTICO",
        Mes: "2/2019",
    },
    {
        Id: 4925,
        Codigo: "CCDG-005",
        Registro: 14434,
        Nombre: 'JONATHAN SALAZAR SALAZAR',
        Dni: 41077947,
        Categoria: "CURSO",
        Programa: "SIGA LOGISTICO",
        Mes: "2/2019",
    },
    {
        Id: 37843,
        Codigo: "CCDG-005",
        Registro: 44249,
        Nombre: 'JUAN DAVID CALIZAYA MAMANI',
        Dni: 43328590,
        Categoria: "Diploma",
        Programa: "SISTEMAS ADMINISTRATIVOS EN GESTIÓN PÚBLICA - SIAF RP, SIGA MEF y OSCE",
        Mes: "11/2022",
    },
    {
        Id: 37842,
        Codigo: " ",
        Registro: 44248,
        Nombre: 'JUAN DAVID CALIZAYA MAMANI',
        Dni: 43328590,
        Categoria: "curso",
        Programa: "PREPARACIÓN PARA LA CERTIFICACIÓN OSCE LEY Nº30225 modificada por D. L. 1444 y su Reglamento D.S. 234-2022-EF",
        Mes: "11/2022",
    },
    {
        Id: 37841,
        Codigo: " ",
        Registro: 44247,
        Nombre: 'LUIS CARLOS TARQUI PAYE',
        Dni: 46237793,
        Categoria: "Diploma",
        Programa: "Sistemas Administrativos en la Gestión Pública SIAF RP, SIGA MEF Y OSCE",
        Mes: "11/2022",
    }
]